In [ ]:
import pandas as pd

# Food Connoisseur

# 1
data1 = {"Apples": [30], "Bananas": 21}
df1 = pd.DataFrame(data=data1)

# 2
data2 = {"Apples": [35,41], "Bananas": [21, 34]}
df2 = pd.DataFrame(data=data2, index=["2017 Sales", "2018 Sales"])

# 3
data3 = ["4 cups", "1 cup", "2 large", "1 can"]
label3 = ["Flour", "Milk", "Eggs", "Spam"]
series3 = pd.Series(data=data3,index=label3)

# 4 
wine_df = pd.read_csv("data/winemag-data_first150k.csv")
wine_df = wine_df.dropna()

In [ ]:
import pandas as pd

# Vroom Vroom

# 1
cars_df = pd.read_csv("data/cars.csv")

# 2
userNum = int(input("Enter a number to subset cars_df: "))
cars_df_subset = cars_df[0:userNum]

# 3 
print(cars_df_subset.max())

# 4
cyl = int(input("Enter a number for cyl: "))
df_cyl = cars_df[cars_df["cyl"] == cyl]

# 5
print(df_cyl.shape)

In [2]:
import pandas as pd

# Taking off?

# 1
flight_df = pd.read_csv("data/Flight_Delay.csv")

# 2
print(flight_df.info())
print(flight_df.describe())

# 2a
print(flight_df.info())
# FL_DATA: object
# UNIQUE_CARRIER: object
# AIRLINE_ID: int64
# TAIL_NUM: object
# FL_NUM: int64
# ORIGIN_AIRPORT_ID: int64
# ORIGIN_AIRPORT_SEQ_ID: int64
# ORIGIN_CITY_MARKET_ID: int64
# ORIGIN: object
# ORIGIN_CITY_NAME: object
# DEST_AIRPORT_ID: int64
# DEST_AIRPORT_SEQ_ID: int64
# DEST_CITY_MARKET_ID: int64
# DEST: object
# DEST_CITY_NAME: object
# CRS_DEP_TIME: int64
# DEP_TIME: float64
# DEP_DELAY: float64
# TAXI_OUT: float64
# WHEELS_OFF: float64
# WHEELS_ON: float64
# TAXI_IN: float64
# CRS_ARR_TIME: int64
# ARR_TIME: float64
# ARR_DELAY: float64
# CANCELLED: float64
# CANCELLATION_CODE: object
# CARRIER_DELAY: float64
# WEATHER_DELAY: float64
# NAS_DELAY: float64
# SECURITY_DELAY: float64
# LATE_AIRCRAFT_DELAY: float64

# 2b
print(flight_df.info())
# if non-null count of column < 450017, it has missing values
# TAIL_NUM: has missing values
# DEP_TIME: has missing values
# DEP_DELAY: has missing values
# TAXI_OUT: has missing values
# WHEELS_OFF: has missing values
# WHEELS_ON: has missing values
# TAXI_IN: has missing values
# ARR_TIME: has missing values
# ARR_DELAY: has missing values
# CANCELLATION_CODE: has missing values
# CARRIER_DELAY: has missing values
# WEATHER_DELAY: has missing values
# NAS_DELAY: has missing values
# SECURITY_DELAY: has missing values
# LATE_AIRCRAFT_DELAY: has missing values
# Unnamed: 32: has missing values

# 2c
len(flight_df["UNIQUE_CARRIER"].unique())
# 12

# 2d
len(flight_df["ORIGIN_AIRPORT_ID"].unique())
# 298

# 3
flight_df[flight_df["CANCELLED"] == 0]

# 4/4a
flight_df["DELAY_DELTA"] = flight_df["ARR_DELAY"] - flight_df["DEP_DELAY"]

# 5
carrier_list = flight_df["UNIQUE_CARRIER"].unique()

# 5a
print(flight_df["UNIQUE_CARRIER"].value_counts())

# 5b
for carrier in carrier_list:
    print(carrier,end=" ")
    print(flight_df[flight_df["UNIQUE_CARRIER"] == carrier]["DELAY_DELTA"].mean())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450017 entries, 0 to 450016
Data columns (total 33 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   FL_DATE                450017 non-null  object
 1   UNIQUE_CARRIER         450017 non-null  object
 2   AIRLINE_ID             450017 non-null  int64
 3   TAIL_NUM               449378 non-null  object
 4   FL_NUM                 450017 non-null  int64
 5   ORIGIN_AIRPORT_ID      450017 non-null  int64
 6   ORIGIN_AIRPORT_SEQ_ID  450017 non-null  int64
 7   ORIGIN_CITY_MARKET_ID  450017 non-null  int64
 8   ORIGIN                 450017 non-null  object
 9   ORIGIN_CITY_NAME       450017 non-null  object
 10  DEST_AIRPORT_ID        450017 non-null  int64
 11  DEST_AIRPORT_SEQ_ID    450017 non-null  int64
 12  DEST_CITY_MARKET_ID    450017 non-null  int64
 13  DEST                   450017 non-null  object
 14  DEST_CITY_NAME         450017 non-null  object
 15  CRS_DEP_TIME           450017 non-null  int64
 16  DEP_TIME               441476 non-null  float64
 17  DEP_DELAY              441476 non-null  float64
 18  TAXI_OUT               441244 non-null  float64
 19  WHEELS_OFF             441244 non-null  float64
 20  WHEELS_ON              440746 non-null  float64
 21  TAXI_IN                440746 non-null  float64
 22  CRS_ARR_TIME           450017 non-null  int64
 23  ARR_TIME               440746 non-null  float64
 24  ARR_DELAY              439645 non-null  float64
 25  CANCELLED              450017 non-null  float64
 26  CANCELLATION_CODE      8886 non-null    object
 27  CARRIER_DELAY          97699 non-null   float64
 28  WEATHER_DELAY          97699 non-null   float64
 29  NAS_DELAY              97699 non-null   float64
 30  SECURITY_DELAY         97699 non-null   float64
 31  LATE_AIRCRAFT_DELAY    97699 non-null   float64
 32  Unnamed: 32            0 non-null       float64
dtypes: float64(15), int64(10), object(8)
memory usage: 113.3+ MB
None
          AIRLINE_ID         FL_NUM  ORIGIN_AIRPORT_ID  ORIGIN_AIRPORT_SEQ_ID  \
count  450017.000000  450017.000000      450017.000000           4.500170e+05
mean    19900.483275    2079.643193       12698.267568           1.269830e+06
std       385.381448    1722.700045        1534.326936           1.534324e+05
min     19393.000000       1.000000       10135.000000           1.013503e+06
25%     19690.000000     679.000000       11292.000000           1.129202e+06
50%     19805.000000    1602.000000       12892.000000           1.289204e+06
75%     20304.000000    3034.000000       14057.000000           1.405702e+06
max     21171.000000    7439.000000       16218.000000           1.621801e+06

       ORIGIN_CITY_MARKET_ID  DEST_AIRPORT_ID  DEST_AIRPORT_SEQ_ID  \
count          450017.000000    450017.000000         4.500170e+05
mean            31738.603264     12698.024626         1.269805e+06
std              1286.063689      1534.246611         1.534244e+05
min             30070.000000     10135.000000         1.013503e+06
25%             30647.000000     11292.000000         1.129202e+06
50%             31454.000000     12892.000000         1.289204e+06
75%             32467.000000     14057.000000         1.405702e+06
max             35991.000000     16218.000000         1.621801e+06

       DEST_CITY_MARKET_ID   CRS_DEP_TIME       DEP_TIME  ...   CRS_ARR_TIME  \
count        450017.000000  450017.000000  441476.000000  ...  450017.000000
mean          31738.404640    1327.757407    1333.947392  ...    1506.278285
std            1285.791081     481.548320     494.957196  ...     501.853851
min           30070.000000       5.000000       1.000000  ...       1.000000
25%           30647.000000     917.000000     921.000000  ...    1120.000000
50%           31454.000000    1321.000000    1330.000000  ...    1529.000000
75%           32467.000000    1730.000000    1738.000000  ...    1921.000000
max           35991.000000    2359.000000    2400.000000  ...    2359.000000

            ARR_TIME      ARR_DELAY      CANCELLED  CARRIER_DELAY  \
count  440746.000000  439645.000000  450017.000000   97699.000000
mean     1487.332958       6.954484       0.019746      20.308836
std       523.821795      49.595992       0.139126      60.649157
min         1.000000     -98.000000       0.000000       0.000000
25%      1108.000000     -15.000000       0.000000       0.000000
50%      1521.000000      -5.000000       0.000000       0.000000
75%      1921.000000      11.000000       0.000000      17.000000
max      2400.000000    1944.000000       1.000000    1934.000000

       WEATHER_DELAY     NAS_DELAY  SECURITY_DELAY  LATE_AIRCRAFT_DELAY  \
count   97699.000000  97699.000000    97699.000000         97699.000000
mean        3.368857     15.742495        0.079745            24.947492
std        27.809756     32.328181        2.896287            47.850860
min         0.000000      0.000000        0.000000             0.000000
25%         0.000000      0.000000        0.000000             0.000000
50%         0.000000      4.000000        0.000000             3.000000
75%         0.000000     20.000000        0.000000            31.000000
max      1934.000000   1457.000000      653.000000          1392.000000

       Unnamed: 32
count          0.0
mean           NaN
std            NaN
min            NaN
25%            NaN
50%            NaN
75%            NaN
max            NaN

[8 rows x 25 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450017 entries, 0 to 450016
Data columns (total 33 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   FL_DATE                450017 non-null  object
 1   UNIQUE_CARRIER         450017 non-null  object
 2   AIRLINE_ID             450017 non-null  int64
 3   TAIL_NUM               449378 non-null  object
 4   FL_NUM                 450017 non-null  int64
 5   ORIGIN_AIRPORT_ID      450017 non-null  int64
 6   ORIGIN_AIRPORT_SEQ_ID  450017 non-null  int64
 7   ORIGIN_CITY_MARKET_ID  450017 non-null  int64
 8   ORIGIN                 450017 non-null  object
 9   ORIGIN_CITY_NAME       450017 non-null  object
 10  DEST_AIRPORT_ID        450017 non-null  int64
 11  DEST_AIRPORT_SEQ_ID    450017 non-null  int64
 12  DEST_CITY_MARKET_ID    450017 non-null  int64
 13  DEST                   450017 non-null  object
 14  DEST_CITY_NAME         450017 non-null  object
 15  CRS_DEP_TIME           450017 non-null  int64
 16  DEP_TIME               441476 non-null  float64
 17  DEP_DELAY              441476 non-null  float64
 18  TAXI_OUT               441244 non-null  float64
 19  WHEELS_OFF             441244 non-null  float64
 20  WHEELS_ON              440746 non-null  float64
 21  TAXI_IN                440746 non-null  float64
 22  CRS_ARR_TIME           450017 non-null  int64
 23  ARR_TIME               440746 non-null  float64
 24  ARR_DELAY              439645 non-null  float64
 25  CANCELLED              450017 non-null  float64
 26  CANCELLATION_CODE      8886 non-null    object
 27  CARRIER_DELAY          97699 non-null   float64
 28  WEATHER_DELAY          97699 non-null   float64
 29  NAS_DELAY              97699 non-null   float64
 30  SECURITY_DELAY         97699 non-null   float64
 31  LATE_AIRCRAFT_DELAY    97699 non-null   float64
 32  Unnamed: 32            0 non-null       float64
dtypes: float64(15), int64(10), object(8)
memory usage: 113.3+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450017 entries, 0 to 450016
Data columns (total 33 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   FL_DATE                450017 non-null  object
 1   UNIQUE_CARRIER         450017 non-null  object
 2   AIRLINE_ID             450017 non-null  int64
 3   TAIL_NUM               449378 non-null  object
 4   FL_NUM                 450017 non-null  int64
 5   ORIGIN_AIRPORT_ID      450017 non-null  int64
 6   ORIGIN_AIRPORT_SEQ_ID  450017 non-null  int64
 7   ORIGIN_CITY_MARKET_ID  450017 non-null  int64
 8   ORIGIN                 450017 non-null  object
 9   ORIGIN_CITY_NAME       450017 non-null  object
 10  DEST_AIRPORT_ID        450017 non-null  int64
 11  DEST_AIRPORT_SEQ_ID    450017 non-null  int64
 12  DEST_CITY_MARKET_ID    450017 non-null  int64
 13  DEST                   450017 non-null  object
 14  DEST_CITY_NAME         450017 non-null  object
 15  CRS_DEP_TIME           450017 non-null  int64
 16  DEP_TIME               441476 non-null  float64
 17  DEP_DELAY              441476 non-null  float64
 18  TAXI_OUT               441244 non-null  float64
 19  WHEELS_OFF             441244 non-null  float64
 20  WHEELS_ON              440746 non-null  float64
 21  TAXI_IN                440746 non-null  float64
 22  CRS_ARR_TIME           450017 non-null  int64
 23  ARR_TIME               440746 non-null  float64
 24  ARR_DELAY              439645 non-null  float64
 25  CANCELLED              450017 non-null  float64
 26  CANCELLATION_CODE      8886 non-null    object
 27  CARRIER_DELAY          97699 non-null   float64
 28  WEATHER_DELAY          97699 non-null   float64
 29  NAS_DELAY              97699 non-null   float64
 30  SECURITY_DELAY         97699 non-null   float64
 31  LATE_AIRCRAFT_DELAY    97699 non-null   float64
 32  Unnamed: 32            0 non-null       float64
dtypes: float64(15), int64(10), object(8)
memory usage: 113.3+ MB
None
WN    107785
AA     73132
DL     69813
OO     50146
UA     42403
EV     35037
B6     24602
AS     14711
NK     12570
F9      7760
HA      6276
VX      5782
Name: UNIQUE_CARRIER, dtype: int64
AA -4.081268155725742
B6 -5.580440587449933
EV -4.4791296098660025
HA 0.70996640537514
NK -2.6887696118909994
OO -2.5094803517106303
UA -8.634416016739586
VX -1.9730603448275863
AS -1.7508689003197553
WN -4.15896475687184
DL -9.123093460387555
F9 -4.4284206359678056